os: osx
language: generic
env:
  - PEX_VERBOSE=9
script:
  - python --version
  - pip install -U tox
  - tox -e py27-package
  - unzip -l ./dist/pex27
  - ./dist/pex27 -vvvvvvvvv responses -o responses.pex
  - echo "import pkg_resources; print(pkg_resources.__path__)" | ./responses.pex -
  - unzip -l ./responses.pex
  - echo "import responses; print(repr(dir(responses)))" | ./responses.pex -

