x-pyenv-shard: &x-pyenv-shard
  language: generic
  env: &env >
    PYENV_ROOT="${HOME}/.pyenv_pex"
    PATH="${PYENV_ROOT}/shims:${PATH}"
  cache:
    # The default is 3 minutes (180).
    timeout: 300
    directories:
      - .pyenv_test
      - "${PYENV_ROOT}"
  install: |
    PYENV="${PYENV_ROOT}/bin/pyenv"
    if [ ! -x "${PYENV}" ]; then
      rm -rf ${PYENV_ROOT}
      git clone https://github.com/pyenv/pyenv "${PYENV_ROOT}";
    fi
    "${PYENV}" install --keep --skip-existing ${PYENV_VERSION}
    "${PYENV}" global ${PYENV_VERSION}
    pip install -U tox "setuptools>=36"

x-linux-shard: &x-linux-shard
  <<: *x-pyenv-shard
  os: linux
  sudo: false
  dist: trusty

x-pypy: &x-pypy
  - *env
  - PYENV_VERSION=pypy2.7-6.0.0

# NB: Travis partitions caches using a combination of os, language amd env vars. As such, we do not
# use TOXENV and instead pass the toxenv via -e on the command line. This helps ensure we share
# caches as much as possible (eg: all linux python 2.7.15 shards share a cache).
matrix:
  include:
    - <<: *x-linux-shard
      name: TOXENV=pypy
      env: *x-pypy
      script: ./scripts/ci.sh pypy

    - <<: *x-linux-shard
      name: TOXENV=pypy-integration
      env: *x-pypy
      script: ./scripts/ci.sh pypy-integration
