# Enables support for a docker container-based build
# which should provide faster startup times and beefier
# "machines".
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
dist: trusty

# TRAVIS_PYTHON_VERSION

cache:
  directories:
    - .pyenv_test

x-osx-shard: &x-osx-shard
  os: osx
  osx_image: xcode8.3

matrix:
  include:
    - <<: *x-osx-shard
      env: TOXENV=py27-requests

    - <<: *x-osx-shard
      env: TOXENV=py36-requests

    - <<: *x-osx-shard
      env: TOXENV=py27-integration

    - <<: *x-osx-shard
      env: TOXENV=py36-integration

install:
  - pip install -U tox "setuptools>=36"

script:
  - ./scripts/ci.sh
