x-linux-shard: &x-linux-shard
  os: linux
  sudo: false
  dist: trusty
  language: python
  cache:
    directories:
      - .pyenv_test

x-osx-shard: &x-osx-shard
  os: osx
  language: generic
  cache:
    directories:
      - .pyenv_test
      - ${HOME}/.pyenvpex
  before_install: |
    export PYENV_ROOT="${HOME}/.pyenvpex"
    if [ ! -d "${PYENV_ROOT}" ]; then
      git clone https://github.com/pyenv/pyenv "${PYENV_ROOT}";
    fi
    export PATH="${PYENV_ROOT}/bin:${PATH}"
    pyenv install --keep --skip-existing ${PYENV_VERSION}
    pyenv global ${PYENV_VERSION}

matrix:
  include:
    - <<: *x-linux-shard
      python: "2.7"
      env: TOXENV=style

    - <<: *x-linux-shard
      python: "2.7"
      env: TOXENV=isort-check

    - <<: *x-linux-shard
      python: "2.7"
      env: TOXENV=py27

    - <<: *x-linux-shard
      python: "2.7"
      env: TOXENV=py27-subprocess

    - <<: *x-linux-shard
      python: "2.7"
      env: TOXENV=py27-requests

    - <<: *x-linux-shard
      python: "2.7"
      env: TOXENV=py27-requests-cachecontrol

    - <<: *x-linux-shard
      python: "3.4"
      env: TOXENV=py34

    - <<: *x-linux-shard
      python: "3.5"
      env: TOXENV=py35

    - <<: *x-linux-shard
      python: "3.6"
      env: TOXENV=py36

    - <<: *x-linux-shard
      python: "3.6"
      env: TOXENV=py36-requests

    - <<: *x-linux-shard
      python: "3.6"
      env: TOXENV=py36-requests-cachecontrol

    - <<: *x-linux-shard
      python: "pypy"
      env: TOXENV=pypy

    - <<: *x-linux-shard
      python: "2.7"
      env: TOXENV=py27-integration

    - <<: *x-linux-shard
      python: "3.6"
      env: TOXENV=py36-integration

    - <<: *x-linux-shard
      python: "pypy"
      env: TOXENV=pypy-integration

    - <<: *x-osx-shard
      name: TOXENV=py27-requests
      env:
        - PYENV_ROOT="${HOME}/.pyenvpex" PATH="${PYENV_ROOT}/shims:${PATH}"
        - PYENV_VERSION=2.7.15
        - TOXENV=py27-requests

    - <<: *x-osx-shard
      name: TOXENV=py36-requests
      env:
        - PYENV_ROOT="${HOME}/.pyenvpex" PATH="${PYENV_ROOT}/shims:${PATH}"
        - PYENV_VERSION=3.6.6
        - TOXENV=py36-requests

    - <<: *x-osx-shard
      name: TOXENV=py27-integration
      env:
        - PYENV_ROOT="${HOME}/.pyenvpex" PATH="${PYENV_ROOT}/shims:${PATH}"
        - PYENV_VERSION=2.7.15
        - TOXENV=py27-integration

    - <<: *x-osx-shard
      name: TOXENV=py36-integration
      env:
        - PYENV_ROOT="${HOME}/.pyenvpex" PATH="${PYENV_ROOT}/shims:${PATH}"
        - PYENV_VERSION=3.6.6
        - TOXENV=py36-integration

install:
  - pip install -U tox "setuptools>=36"

script:
  - ./scripts/ci.sh
