# Enables support for a docker container-based build
# which should provide faster startup times and beefier
# "machines".
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
dist: trusty

# TRAVIS_PYTHON_VERSION

cache:
  directories:
    - .pyenv_test

x-linux-shard: &x-linux-shard
  os: linux
  language: python

x-osx-shard: &x-osx-shard
  os: osx
  osx_image: xcode8.3

matrix:
  include:
    - <<: *x-linux-shard
      python: "2.7"
      env: TOXENV=style

    - <<: *x-linux-shard
      python: "2.7"
      env: TOXENV=isort-check

    - <<: *x-linux-shard
      python: "2.7"
      env: TOXENV=py27

    - <<: *x-linux-shard
      python: "2.7"
      env: TOXENV=py27-subprocess

    - <<: *x-linux-shard
      python: "2.7"
      env: TOXENV=py27-requests

    - <<: *x-osx-shard
      env: TOXENV=py27-requests

    - <<: *x-linux-shard
      python: "2.7"
      env: TOXENV=py27-requests-cachecontrol

    - <<: *x-linux-shard
      python: "3.4"
      env: TOXENV=py34

    - <<: *x-linux-shard
      python: "3.5"
      env: TOXENV=py35

    - <<: *x-linux-shard
      python: "3.6"
      env: TOXENV=py36

    - <<: *x-linux-shard
      python: "3.6"
      env: TOXENV=py36-requests

    - <<: *x-osx-shard
      env: TOXENV=py36-requests

    - <<: *x-linux-shard
      python: "3.6"
      env: TOXENV=py36-requests-cachecontrol

    - <<: *x-linux-shard
      python: "pypy"
      env: TOXENV=pypy

    - <<: *x-linux-shard
      python: "2.7"
      env: TOXENV=py27-integration

    - <<: *x-osx-shard
      env: TOXENV=py27-integration

    - <<: *x-linux-shard
      python: "3.6"
      env: TOXENV=py36-integration

    - <<: *x-osx-shard
      env: TOXENV=py36-integration

    - <<: *x-linux-shard
      python: "pypy"
      env: TOXENV=pypy-integration

install:
  - pip install -U tox "setuptools>=36"

script:
  - ./scripts/ci.sh
