# Enables support for a docker container-based build
# which should provide faster startup times and beefier
# "machines".
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
dist: trusty

cache:
  directories:
    - .pyenv_test

linux: &linux
  os: linux
  language: python

osx: &osx
  os: osx
  language: generic
  before_install:
    - brew install readline xz
    - xcode-select --install
    - brew install openssl pyenv

matrix:
  include:
    - <<: *osx
      env: TOXENV=py27

    - <<: *osx
      env: TOXENV=py36

    - <<: *osx
      env: TOXENV=py27-integration

    - <<: *osx
      env: TOXENV=py36-integration

    - <<: *linux
      python: "2.7"
      env: TOXENV=style

    - <<: *linux
      python: "2.7"
      env: TOXENV=isort-check

    - <<: *linux
      python: "2.7"
      env: TOXENV=py27

    - <<: *linux
      python: "2.7"
      env: TOXENV=py27-subprocess

    - <<: *linux
      python: "2.7"
      env: TOXENV=py27-requests

    - <<: *linux
      python: "2.7"
      env: TOXENV=py27-requests-cachecontrol

    - <<: *linux
      python: "3.4"
      env: TOXENV=py34

    - <<: *linux
      python: "3.5"
      env: TOXENV=py35

    - <<: *linux
      python: "3.6"
      env: TOXENV=py36

    - <<: *linux
      python: "3.6"
      env: TOXENV=py36-requests

    - <<: *linux
      python: "3.6"
      env: TOXENV=py36-requests-cachecontrol

    - <<: *linux
      python: "pypy"
      env: TOXENV=pypy

    - <<: *linux
      python: "2.7"
      env: TOXENV=py27-integration

    - <<: *linux
      python: "3.6"
      env: TOXENV=py36-integration

    - <<: *linux
      python: "pypy"
      env: TOXENV=pypy-integration

install:
  - pip install -U tox "setuptools>=36"

script:
  - ./scripts/ci.sh
