# Enables support for a docker container-based build
# which should provide faster startup times and beefier
# "machines".
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
dist: trusty

# TRAVIS_PYTHON_VERSION

cache:
  directories:
    - .pyenv_test

x-osx-shard: &x-osx-shard
  os: osx
  osx_image: xcode8.3
  language: generic
  cache:
    directories:
      - ${HOME}/.pyenv
  before_install: |
    export PYENV_ROOT="${HOME}/.pyenv"
    if [ ! -d "${PYENV_ROOT}" ]; then
      git clone https://github.com/pyenv/pyenv "${PYENV_ROOT}";
    fi
    export PATH="${PYENV_ROOT}/bin:${PATH}"
    pyenv install --keep --skip-existing ${PYENV_VERSION}
    pyenv global ${PYENV_VERSION}

matrix:
  include:
    - <<: *x-osx-shard
      env:
        - PYENV_ROOT="${HOME}/.pyenv" PATH="${PYENV_ROOT}/shims:${PATH}"
        - PYENV_VERSION=2.7.15
        - TOXENV=py27-requests

    - <<: *x-osx-shard
      env:
        - PYENV_ROOT="${HOME}/.pyenv" PATH="${PYENV_ROOT}/shims:${PATH}"
        - PYENV_VERSION=3.6.6
        - TOXENV=py36-requests

    - <<: *x-osx-shard
      env:
        - PYENV_ROOT="${HOME}/.pyenv" PATH="${PYENV_ROOT}/shims:${PATH}"
        - PYENV_VERSION=2.7.15
        - TOXENV=py27-integration

    - <<: *x-osx-shard
      env:
        - PYENV_ROOT="${HOME}/.pyenv" PATH="${PYENV_ROOT}/shims:${PATH}"
        - PYENV_VERSION=3.6.6
        - TOXENV=py36-integration

install:
  - pip install -U tox "setuptools>=36"

script:
  - ./scripts/ci.sh
