cache:
  directories:
    - .pyenv_test

x-osx-shard: &x-osx-shard
  os: osx
  language: generic
  cache:
    directories:
      - ${HOME}/.pyenv
  before_install: |
    export PYENV_ROOT="${HOME}/.pyenvpex"
    if [ ! -d "${PYENV_ROOT}" ]; then
      git clone https://github.com/pyenv/pyenv "${PYENV_ROOT}";
    fi
    export PATH="${PYENV_ROOT}/bin:${PATH}"
    pyenv install --keep --skip-existing ${PYENV_VERSION}
    pyenv global ${PYENV_VERSION}

matrix:
  include:
    - <<: *x-osx-shard
      name: TOXENV=py27-requests
      env:
        - PYENV_ROOT="${HOME}/.pyenvpex" PATH="${PYENV_ROOT}/shims:${PATH}"
        - PYENV_VERSION=2.7.15
        - TOXENV=py27-requests

    - <<: *x-osx-shard
      name: TOXENV=py36-requests
      env:
        - PYENV_ROOT="${HOME}/.pyenvpex" PATH="${PYENV_ROOT}/shims:${PATH}"
        - PYENV_VERSION=3.6.6
        - TOXENV=py36-requests

    - <<: *x-osx-shard
      name: TOXENV=py27-integration
      env:
        - PYENV_ROOT="${HOME}/.pyenvpex" PATH="${PYENV_ROOT}/shims:${PATH}"
        - PYENV_VERSION=2.7.15
        - TOXENV=py27-integration

    - <<: *x-osx-shard
      name: TOXENV=py36-integration
      env:
        - PYENV_ROOT="${HOME}/.pyenvpex" PATH="${PYENV_ROOT}/shims:${PATH}"
        - PYENV_VERSION=3.6.6
        - TOXENV=py36-integration

install:
  - pip install -U tox "setuptools>=36"

script:
  - ./scripts/ci.sh
