build: false

environment:
  matrix:
    - PYTHON: C:\Python27
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 64

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install tox"

test_script:
  - "%PYTHON%/Scripts/tox -e isort-check,style,py27-requests,py27-integration"
