name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash
env:
  _PEX_TEST_PYENV_ROOT: .pyenv_test
  # We use this to skip exposing same-versioned Pythons present on Linux hosts. These otherwise can
  # collide when attempting to load libpython<major>.<minor><flags>.so and lead to mysterious errors
  # importing builtins like `fcntl` as outlined in https://github.com/pantsbuild/pex/issues/1391.
  _PEX_TEST_PYENV_VERSIONS: "2.7 3.7 3.10"
concurrency:
  group: CI-${{ github.ref }}
  # Queue on all branches and tags, but only cancel overlapping PR burns.
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' || !startsWith(github.ref, 'refs/tags/') }}
jobs:
  org-check:
    name: Check GitHub Organization
    if: github.repository_owner == 'pantsbuild'
    runs-on: ubuntu-20.04
    steps:
      - name: Noop
        run: "true"
  cpython-integration-tests:
    name: (${{ matrix.os }}) TOXENV=py${{ matrix.python-version[0] }}${{ matrix.python-version[1] }}-integration
    needs: org-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [[2, 7], [3, 10], [3, 11, "0-beta.4"]]
        os: [ubuntu-20.04, macos-11]
        exclude:
          - os: macos-11
            python-version: [3, 11, "0-beta.4"]
    steps:
      - name: Calculate Pythons to Expose
        id: calculate-pythons-to-expose
        run: |
          skip=""
          if [[ "$(uname -s)" == "Linux" ]]; then
            skip="${{ env._PEX_TEST_PYENV_VERSIONS }}"
          fi
          echo "::set-output name=skip::${skip}"
      - name: Checkout Pex
        uses: actions/checkout@v2
        with:
          # We need branches and tags for some ITs.
          fetch-depth: 0
      - name: Setup Python ${{ join(matrix.python-version, '.') }}
        uses: actions/setup-python@v3
        with:
          python-version: "${{ join(matrix.python-version, '.') }}"
      - name: Expose Pythons
        uses: pantsbuild/actions/expose-pythons@4c36480012d4d430c9d865222cdb2b6d91713acd
        with:
          skip: "${{ steps.calculate-pythons-to-expose.outputs.skip }}"
      - name: Cache Pyenv Interpreters
        uses: actions/cache@v2
        with:
          path: ${{ env._PEX_TEST_PYENV_ROOT }}
          key: ${{ runner.os }}-pyenv-root-v3
      - name: Run Integration Tests
        uses: pantsbuild/actions/run-tox@95209b287c817c78a765962d40ac6cea790fc511
        with:
          tox-env: py${{ matrix.python-version[0] }}${{ matrix.python-version[1] }}-integration -- -vvsk test_issue_1872 -n0
  pypy-integration-tests:
    name: (PyPy ${{ join(matrix.pypy-version, '.') }}) TOXENV=pypy${{ join(matrix.pypy-version, '') }}-integration
    needs: org-check
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        pypy-version: [[2, 7], [3, 9]]
    steps:
      - name: Calculate Pythons to Expose
        id: calculate-pythons-to-expose
        run: |
          skip=""
          if [[ "$(uname -s)" == "Linux" ]]; then
            skip="${{ env._PEX_TEST_PYENV_VERSIONS }}"
          fi
          echo "::set-output name=skip::${skip}"
      - name: Checkout Pex
        uses: actions/checkout@v2
        with:
          # We need branches and tags for some ITs.
          fetch-depth: 0
      - name: Setup PyPy ${{ join(matrix.pypy-version, '.') }}
        uses: actions/setup-python@v3
        with:
          python-version: "pypy-${{ join(matrix.pypy-version, '.') }}"
      - name: Expose Pythons
        uses: pantsbuild/actions/expose-pythons@4c36480012d4d430c9d865222cdb2b6d91713acd
        with:
          skip: "${{ steps.calculate-pythons-to-expose.outputs.skip }}"
      - name: Install Packages
        run: |
          # This is needed for `test_requirement_file_from_url` for building `lxml`.
          sudo apt install --yes libxslt-dev
      - name: Cache Pyenv Interpreters
        uses: actions/cache@v2
        with:
          path: ${{ env._PEX_TEST_PYENV_ROOT }}
          key: ${{ runner.os }}-pyenv-root-v3
      - name: Run Integration Tests
        uses: pantsbuild/actions/run-tox@95209b287c817c78a765962d40ac6cea790fc511
        with:
          tox-env: pypy${{ join(matrix.pypy-version, '') }}-integration -- -vvsk test_issue_1872 -n0
  final-status:
    name: Gather Final Status
    needs:
      - cpython-integration-tests
      - pypy-integration-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Check Non-Success
        if: |
          contains(needs.*.result, 'cancelled') ||
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'skipped')
        run: "false"
      - name: Success
        run: "true"
