name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash
env:
  _PEX_TEST_PYENV_ROOT: .pyenv_test
  # We use this to skip exposing same-versioned Pythons present on Linux hosts. These otherwise can
  # collide when attempting to load libpython<major>.<minor><flags>.so and lead to mysterious errors
  # importing builtins like `fcntl` as outlined in https://github.com/pantsbuild/pex/issues/1391.
  _PEX_TEST_PYENV_VERSIONS: "2.7 3.7 3.10"
concurrency:
  group: CI-${{ github.ref }}
  # Queue on all branches and tags, but only cancel overlapping PR burns.
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' || !startsWith(github.ref, 'refs/tags/') }}
jobs:
  cpython-integration-tests:
    name: (${{ matrix.os }}) TOXENV=py${{ matrix.python-version[0] }}${{ matrix.python-version[1] }}-integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [[2, 7]]
        os: [macos-11]
    steps:
      - name: Calculate Pythons to Expose
        id: calculate-pythons-to-expose
        run: |
          skip=""
          if [[ "$(uname -s)" == "Linux" ]]; then
            skip="${{ env._PEX_TEST_PYENV_VERSIONS }}"
          fi
          echo "::set-output name=skip::${skip}"
      - name: Checkout Pex
        uses: actions/checkout@v2
        with:
          # We need branches and tags for some ITs.
          fetch-depth: 0
      - name: Setup Python ${{ join(matrix.python-version, '.') }}
        uses: actions/setup-python@v3
        with:
          python-version: "${{ join(matrix.python-version, '.') }}"
      - name: Expose Pythons
        uses: pantsbuild/actions/expose-pythons@4c36480012d4d430c9d865222cdb2b6d91713acd
        with:
          skip: "${{ steps.calculate-pythons-to-expose.outputs.skip }}"
      - name: Cache Pyenv Interpreters
        uses: actions/cache@v2
        with:
          path: ${{ env._PEX_TEST_PYENV_ROOT }}
          key: ${{ runner.os }}-pyenv-root-v4
      - name: Run Integration Tests
        uses: pantsbuild/actions/run-tox@95209b287c817c78a765962d40ac6cea790fc511
        with:
          tox-env: py${{ matrix.python-version[0] }}${{ matrix.python-version[1] }}-integration
