name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash
env:
  _PEX_TEST_DEV_ROOT: ${{ github.workspace }}/.pex_dev
  _PEX_TEST_POS_ARGS: "--color --devpi --devpi-timeout 15.0 --shutdown-devpi -vvs"
  _PEX_PEXPECT_TIMEOUT: 10
  # We have integration tests that exercise `--scie` support and these can trigger downloads from
  # GitHub Releases that needed elevated rate limit quota, which this gives.
  SCIENCE_AUTH_API_GITHUB_COM_BEARER: ${{ secrets.GITHUB_TOKEN }}
concurrency:
  group: CI-${{ github.ref }}
  # Queue on all branches and tags, but only cancel overlapping PR burns.
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}
jobs:
  org-check:
    name: Check GitHub Organization
    if: github.repository_owner == 'pex-tool'
    runs-on: ubuntu-24.04
    steps:
      - name: Noop
        run: "true"

  # N.B.: The name of this job key (linux-tests) is depended on by scrips/build_cache_image.py. In
  # particular, the tox-env matrix list is used to ensure the cache covers all Linux CI jobs.
  linux-tests:
    name: ./dtox.sh -e ${{ matrix.tox-env }} ${{ matrix.pex-test-pos-args }}
    needs: org-check
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - tox-env: py314-pip24_3_1-integration
            pex-test-pos-args: -k test_mount_respects_env -n0
    steps:
      - name: Free Up Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: true # ~14GB
          dotnet: true # ~2GB
          tool-cache: true # ~12GB

          # Too little space savings or too slow.
          haskell: false
          large-packages: false
          docker-images: false
          swap-storage: false
      - name: Checkout Pex
        uses: actions/checkout@v4
        with:
          # We need branches and tags for some ITs.
          fetch-depth: 0
      # Some ITs need this for VCS URLs of the form git+ssh://git@github.com/...
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        if: env.SSH_PRIVATE_KEY != ''
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}
      - name: Run Tests
        run: |
          # This is needed to get pexpect tests working under PyPy running under docker.
          export TERM="xterm"
          BASE_MODE=pull CACHE_MODE=pull \
            ./dtox.sh -e ${{ matrix.tox-env }} -- \
              ${{ env._PEX_TEST_POS_ARGS }} ${{ matrix.pex-test-pos-args }}
  mac-tests:
    name: tox -e ${{ matrix.tox-env }} ${{ matrix.pex-test-pos-args }}
    needs: org-check
    runs-on: macos-13
    strategy:
      matrix:
        include:
          - python-version: [ 3, 13 ]
            tox-env: py313-pip24_3_1-integration
            tox-env-python: python3.11
            pex-test-pos-args: -k test_mount_respects_env -n0
    steps:
      - name: Checkout Pex
        uses: actions/checkout@v4
        with:
          # We need branches and tags for some ITs.
          fetch-depth: 0
          path: repo
      - name: Setup Python ${{ join(matrix.python-version, '.') }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ join(matrix.python-version, '.') }}"
      - name: Expose Pythons
        uses: pantsbuild/actions/expose-pythons@e63d2d0e3c339bdffbe5e51e7c39550e3bc527bb
      - name: Restore Cached Pyenv Interpreters
        id: restore-pyenv-interpreters
        uses: actions/cache/restore@v4
        with:
          path: ${{ env._PEX_TEST_DEV_ROOT }}/pyenv
          key: macos-13-${{ runner.arch }}-pex-test-dev-root-pyenv-v1
      - name: Restore Cached Devpi Server
        id: restore-devpi-server
        uses: actions/cache/restore@v4
        with:
          path: ${{ env._PEX_TEST_DEV_ROOT }}/devpi
          # We're using a key suffix / restore-keys prefix trick here to get an updatable cache.
          # See: https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
          key: macos-13-${{ runner.arch }}-${{ matrix.tox-env }}-pex-test-dev-root-devpi-v1-${{ github.run_id }}
          restore-keys: macos-13-${{ runner.arch }}-${{ matrix.tox-env }}-pex-test-dev-root-devpi-v1
      # Some ITs need this for VCS URLs of the form git+ssh://git@github.com/...
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        if: env.SSH_PRIVATE_KEY != ''
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}
      - name: Run Tests
        uses: pantsbuild/actions/run-tox@b16b9cf47cd566acfe217b1dafc5b452e27e6fd7
        with:
          path: repo/tox.ini
          python: ${{ matrix.tox-env-python }}
          tox-env: >-
            ${{ matrix.tox-env }} -- ${{ env._PEX_TEST_POS_ARGS }} ${{ matrix.pex-test-pos-args }}
      - name: Cache Pyenv Interpreters
        uses: actions/cache/save@v4
        if: github.ref == 'refs/heads/main'
        with:
          path: ${{ env._PEX_TEST_DEV_ROOT }}/pyenv
          key: ${{ steps.restore-pyenv-interpreters.outputs.cache-primary-key }}
      - name: Cache Devpi Server
        uses: actions/cache/save@v4
        if: github.ref == 'refs/heads/main'
        with:
          path: ${{ env._PEX_TEST_DEV_ROOT }}/devpi
          key: ${{ steps.restore-devpi-server.outputs.cache-primary-key }}
  final-status:
    name: Gather Final Status
    needs:
      - linux-tests
      - mac-tests
    runs-on: ubuntu-24.04
    steps:
      - name: Check Non-Success
        if: |
          contains(needs.*.result, 'cancelled') ||
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'skipped')
        run: "false"
      - name: Success
        run: "true"
